SELECT * FROM MANAGER1;
-- FINDING THE 2ND LARGEST SALARY FROM MANAGER1 TABLE
SELECT NAME, SALARY FROM MANAGER1 ORDER BY SALARY DESC LIMIT 1,1;

-- FINDING THE 3RD LARGEST SALARY FROM MANAGER1 TABLE
SELECT NAME,SALARY FROM MANAGER1 ORDER BY SALARY DESC LIMIT 2,1;

-- FINDING THE 4TH LARGEST SALARY FROM MANAGER1 TABLE
SELECT NAME,SALARY FROM MANAGER1 ORDER BY SALARY DESC LIMIT 3,1;

-- FINDING THE 1ST LARGEST SALARY FROM MANAGER1 TABLE
SELECT NAME,SALARY FROM MANAGER1 ORDER BY SALARY DESC LIMIT 0,1;

CREATE TABLE ORDERS1(
ORDER_ID INT,ORDER_DATE DATE,CUSTOMER_ID INT);
CREATE TABLE CUSTOMER1(
CUS_ID INT ,CUS_NAME VARCHAR(30),CONTACT_NAME VARCHAR(40),COUNTRY VARCHAR(30));

INSERT INTO ORDERS1 VALUES(110,'2023-5-1',200),(111,'2023-5-2',207),(112,'2023-5-3',201),(114,'2023-5-4',204),(113,'2023-5-5',205);
INSERT INTO CUSTOMER1 VALUES(200,'SWAPNA','SUBBAREDDY','INDIA'),(201,'SAMRIN','SUBHAN','US'),(204,'RAHUL','SURYA','UK')
,(205,'YAMUNA','ZAIBA','RUSSIA'),(209,'SUMANTH','VANI','INDIA');
SELECT* FROM ORDERS1;
SELECT* FROM CUSTOMER1;

-- JOIN
SELECT ORDERS1.ORDER_ID,CUSTOMER1.CUS_NAME,ORDERS1.ORDER_DATE FROM ORDERS1
INNER JOIN CUSTOMER1 ON ORDERS1.CUSTOMER_ID=CUSTOMER1.CUS_ID;

CREATE TABLE STAFF(
ID INT,NAME VARCHAR(30), AGE INT,PACKAGE INT);

CREATE TABLE PAYMENT(
ID INT,DA_TE DATE,STAFF_ID INT,AMOUNT INT);

INSERT INTO STAFF VALUES(201,'SWAPNA',20,20000),(202,'SWATHI',20,30000),(203,'SUMANTH',21,50000),(204,'RAHUL',22,70000);

INSERT INTO PAYMENT VALUES(300,'2023-05-2',201,10000),(302,'2023-05-3',202,15000),(304,'2023-05-2',203,18000),(305,'2023-05-7',209,40000);
SELECT * FROM STAFF;
SELECT * FROM PAYMENT;

SELECT s.ID,NAME,AGE,AMOUNT FROM STAFF s, PAYMENT p WHERE s.ID=p.STAFF_ID;

ALTER TABLE ORDERS1 ADD SHIPPING_ID INT ;
ALTER TABLE ORDERS1 DROP COLUMN SHIPPIND_ID;
SELECT * FROM ORDERS1;
UPDATE ORDERS1 SET SHIPPING_ID =1234 WHERE ORDER_ID = 110;
UPDATE ORDERS1 SET SHIPPING_ID =8888 WHERE ORDER_ID = 111;
UPDATE ORDERS1 SET SHIPPING_ID =9999 WHERE ORDER_ID = 112;
UPDATE ORDERS1 SET SHIPPING_ID =7777 WHERE ORDER_ID = 114;
UPDATE ORDERS1 SET SHIPPING_ID =6666 WHERE ORDER_ID = 113;

CREATE TABLE SHIPPING(
SHIPPING_ID INT,NAME VARCHAR(37));
INSERT INTO SHIPPING VALUES(1234,'XXX'),(8888,'EXPRESS'),(7777,'YYY'),(6666,'ZZZ'),(8598,'SSS');
SELECT * FROM ORDERS1;
SELECT * FROM CUSTOMER1;
SELECT * FROM SHIPPING;

-- JOINING OF 3 TABLES ORDERS1,CUSTOMER1,SHIPPING

SELECT ORDERS1.ORDER_ID,CUSTOMER1.CUS_NAME,SHIPPING.NAME FROM 
((ORDERS1 INNER JOIN CUSTOMER1 ON ORDERS1.CUSTOMER_ID= CUSTOMER1.CUS_ID)
INNER JOIN SHIPPING ON ORDERS1.SHIPPING_ID = SHIPPING.SHIPPING_ID);

-- LEFT JOIN OF ORDERS1 AND CUSTOMER1 TABLES
SELECT CUSTOMER1.CUS_NAME,ORDERS1.ORDER_ID FROM CUSTOMER1 
LEFT JOIN ORDERS1 ON CUSTOMER1.CUS_ID=ORDERS1.CUSTOMER_ID;

SELECT CUSTOMER1.CUS_NAME,ORDERS1.ORDER_ID FROM CUSTOMER1 
LEFT JOIN ORDERS1 ON CUSTOMER1.CUS_ID=ORDERS1.CUSTOMER_ID ORDER BY CUSTOMER1.CUS_NAME;

select customer1.cus_name,orders1.order_id from customer1
left join orders1 on customer1.cus_id=orders1.customer_id where customer1.cus_name like 'S%' order by customer1.cus_name;



SELECT * FROM CUSTOMER1;
SELECT * FROM ORDERS1;


-- RIGHT JOIN OF ORDERS1 AND CUSTOMER1 TABLES
SELECT CUS_NAME,COUNTRY,ORDER_DATE FROM CUSTOMER1 RIGHT JOIN ORDERS1 ON CUSTOMER1.CUS_ID=ORDERS1.CUSTOMER_ID;
-- FULL JOIN
SELECT CUS_NAME,ORDERS1.ORDER_ID FROM CUSTOMER1 FULL JOIN ORDERS1 ON CUS_ID=ORDERS1.CUSTOMER_ID;

CREATE TABLE TEST(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
C2 VARCHAR(40) NOT NULL,
C3 VARCHAR(40) DEFAULT 'SOFTWARE ENGINEER');




